pages = [{"l":"index.html#","e":false,"i":"","n":"backend","t":"backend","d":"","k":"static","x":""},
{"l":"_empty_/Bishop.html#","e":false,"i":"","n":"Bishop","t":"Bishop(c: String, p: Position) extends Piece","d":"","k":"class","x":""},
{"l":"_empty_/Board.html#","e":false,"i":"","n":"Board","t":"Board","d":"","k":"class","x":""},
{"l":"_empty_/Board.html#board-0","e":false,"i":"","n":"board","t":"board: Array[Array[Piece]]","d":"Board","k":"def","x":""},
{"l":"_empty_/Board.html#initialize-94c","e":false,"i":"","n":"initialize","t":"initialize(): Unit","d":"Board","k":"def","x":""},
{"l":"_empty_/Board.html#movePiece-fffff2a3","e":false,"i":"","n":"movePiece","t":"movePiece(piece: Piece, newPos: Position): Unit","d":"Board","k":"def","x":""},
{"l":"_empty_/Board.html#visualizeBoard-fffff2ca","e":false,"i":"","n":"visualizeBoard","t":"visualizeBoard(side: String): String","d":"Board","k":"def","x":""},
{"l":"_empty_/Castleable.html#","e":false,"i":"","n":"Castleable","t":"Castleable","d":"","k":"trait","x":""},
{"l":"_empty_/Castleable.html#canCastle-0","e":false,"i":"","n":"canCastle","t":"canCastle: Boolean","d":"Castleable","k":"def","x":""},
{"l":"_empty_/Castleable.html#cannotCastle-0","e":false,"i":"","n":"cannotCastle","t":"cannotCastle: Unit","d":"Castleable","k":"def","x":""},
{"l":"_empty_/DataOutputFormat.html#","e":false,"i":"","n":"DataOutputFormat","t":"DataOutputFormat(winner: String, turn: String, board: Map[String, PieceInformation], timesPlay: Map[String, Array[Long]], gameClock: Long)","d":"","k":"class","x":""},
{"l":"_empty_/Game.html#","e":false,"i":"","n":"Game","t":"Game","d":"","k":"class","x":""},
{"l":"_empty_/Game.html#board-0","e":false,"i":"","n":"board","t":"board: Board","d":"Game","k":"def","x":""},
{"l":"_empty_/Game.html#colorPiece-0","e":false,"i":"","n":"colorPiece","t":"colorPiece: String => List[Piece]","d":"Game","k":"val","x":""},
{"l":"_empty_/Game.html#convertPos-fffff617","e":false,"i":"","n":"convertPos","t":"convertPos(input: String): (Int, Int)","d":"Game","k":"def","x":""},
{"l":"_empty_/Game.html#play-94c","e":false,"i":"","n":"play","t":"play(): Unit","d":"Game","k":"def","x":""},
{"l":"_empty_/Game.html#validPosition-fffffd1b","e":false,"i":"","n":"validPosition","t":"validPosition(input: String): Boolean","d":"Game","k":"def","x":""},
{"l":"_empty_/Game.html#winner-0","e":false,"i":"","n":"winner","t":"winner: String","d":"Game","k":"def","x":""},
{"l":"_empty_/GameAPI.html#","e":false,"i":"","n":"GameAPI","t":"GameAPI","d":"","k":"class","x":""},
{"l":"_empty_/GameAPI.html#board-0","e":false,"i":"","n":"board","t":"board: Board","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#colorPiece-0","e":false,"i":"","n":"colorPiece","t":"colorPiece: String => List[Piece]","d":"GameAPI","k":"val","x":""},
{"l":"_empty_/GameAPI.html#convertForFrontend-fffff328","e":false,"i":"","n":"convertForFrontend","t":"convertForFrontend(): Map[String, PieceInformation]","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#convertPos-fffff617","e":false,"i":"","n":"convertPos","t":"convertPos(input: String): (Int, Int)","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#initialize-94c","e":false,"i":"","n":"initialize","t":"initialize(): Unit","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#play-c17","e":false,"i":"","n":"play","t":"play(selectedSquare: String, targetSquare: String, promotion: String): Map[String, PieceInformation]","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#setWinner-571","e":false,"i":"","n":"setWinner","t":"setWinner(newWinner: String): Unit","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#timesPlay-0","e":false,"i":"","n":"timesPlay","t":"timesPlay: Map[String, Array[Long]]","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#turn-0","e":false,"i":"","n":"turn","t":"turn: String","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#validPosition-fffffd1b","e":false,"i":"","n":"validPosition","t":"validPosition(input: String): Boolean","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/GameAPI.html#winner-0","e":false,"i":"","n":"winner","t":"winner: String","d":"GameAPI","k":"def","x":""},
{"l":"_empty_/King.html#","e":false,"i":"","n":"King","t":"King(c: String, p: Position) extends Piece, Castleable","d":"","k":"class","x":""},
{"l":"_empty_/King.html#isChecked-9a0","e":false,"i":"","n":"isChecked","t":"isChecked(friendlyPieces: List[Piece], enemiesPieces: List[Piece]): Boolean","d":"King","k":"def","x":""},
{"l":"_empty_/King.html#valideCastle-cb7","e":false,"i":"","n":"valideCastle","t":"valideCastle(targetPosition: Position, friendlyPieces: List[Piece], enemiesPieces: List[Piece]): Boolean","d":"King","k":"def","x":""},
{"l":"_empty_/Knight.html#","e":false,"i":"","n":"Knight","t":"Knight(c: String, p: Position) extends Piece","d":"","k":"class","x":""},
{"l":"_empty_/Main$.html#","e":false,"i":"","n":"Main","t":"Main extends IOApp","d":"","k":"object","x":""},
{"l":"_empty_/Main$.html#corsService-0","e":false,"i":"","n":"corsService","t":"corsService: Http[IO, IO]","d":"Main","k":"val","x":""},
{"l":"_empty_/Main$.html#game-0","e":false,"i":"","n":"game","t":"game: GameAPI","d":"Main","k":"val","x":""},
{"l":"_empty_/Main$.html#helloWorldService-0","e":false,"i":"","n":"helloWorldService","t":"helloWorldService: Kleisli[IO, Request[IO], Response[IO]]","d":"Main","k":"val","x":""},
{"l":"_empty_/Main$.html#run-fffffa24","e":false,"i":"","n":"run","t":"run(args: List[String]): IO[ExitCode]","d":"Main","k":"def","x":""},
{"l":"_empty_/Main$.html#server-0","e":false,"i":"","n":"server","t":"server: Resource[IO, Server]","d":"Main","k":"val","x":""},
{"l":"_empty_/Pawn.html#","e":false,"i":"","n":"Pawn","t":"Pawn(c: String, p: Position) extends Piece","d":"","k":"class","x":""},
{"l":"_empty_/Pawn.html#enPassant-0","e":false,"i":"","n":"enPassant","t":"enPassant: Boolean","d":"Pawn","k":"def","x":""},
{"l":"_empty_/Pawn.html#enPassant_-8ac","e":false,"i":"","n":"enPassant_","t":"enPassant_(target: Boolean): Unit","d":"Pawn","k":"def","x":""},
{"l":"_empty_/Pawn.html#promote-b89","e":false,"i":"","n":"promote","t":"promote(kind: String): Piece","d":"Pawn","k":"def","x":""},
{"l":"_empty_/Piece.html#","e":false,"i":"","n":"Piece","t":"Piece(c: String, p: Position)","d":"","k":"class","x":""},
{"l":"_empty_/Piece.html#availableMovements-e92","e":false,"i":"","n":"availableMovements","t":"availableMovements(friendlyPieces: List[Piece], enemiesPieces: List[Piece]): List[Position]","d":"Piece","k":"def","x":""},
{"l":"_empty_/Piece.html#color-0","e":false,"i":"","n":"color","t":"color: String","d":"Piece","k":"def","x":""},
{"l":"_empty_/Piece.html#isValidMovement-ae0","e":false,"i":"","n":"isValidMovement","t":"isValidMovement(targetPosition: Position, friendlyPieces: List[Piece], enemiesPieces: List[Piece], friendlyKing: King): Boolean","d":"Piece","k":"def","x":""},
{"l":"_empty_/Piece.html#longRangeMovements-0","e":false,"i":"","n":"longRangeMovements","t":"longRangeMovements: (List[Piece], List[Piece], Int, Int) => List[Position]","d":"Piece","k":"val","x":""},
{"l":"_empty_/Piece.html#move-f55","e":false,"i":"","n":"move","t":"move(newPos: Position): Unit","d":"Piece","k":"def","x":""},
{"l":"_empty_/Piece.html#move-d2c","e":false,"i":"","n":"move","t":"move(newRow: Int, newColumn: Int): Unit","d":"Piece","k":"def","x":""},
{"l":"_empty_/Piece.html#position-0","e":false,"i":"","n":"position","t":"position: Position","d":"Piece","k":"def","x":""},
{"l":"_empty_/PieceInformation.html#","e":false,"i":"","n":"PieceInformation","t":"PieceInformation(pieceType: String, pieceColor: String, availableMovements: List[String], isChecked: Boolean)","d":"","k":"class","x":""},
{"l":"_empty_/PieceMovement.html#","e":false,"i":"","n":"PieceMovement","t":"PieceMovement(selectedSquare: String, targetSquare: String)","d":"","k":"class","x":""},
{"l":"_empty_/Position.html#","e":false,"i":"","n":"Position","t":"Position(x: Int, y: Int)","d":"","k":"class","x":""},
{"l":"_empty_/Position.html#column-0","e":false,"i":"","n":"column","t":"column: Int","d":"Position","k":"def","x":""},
{"l":"_empty_/Position.html#move-d2c","e":false,"i":"","n":"move","t":"move(newRow: Int, newColumn: Int): Unit","d":"Position","k":"def","x":""},
{"l":"_empty_/Position.html#move-f55","e":false,"i":"","n":"move","t":"move(newPos: Position): Unit","d":"Position","k":"def","x":""},
{"l":"_empty_/Position.html#row-0","e":false,"i":"","n":"row","t":"row: Int","d":"Position","k":"def","x":""},
{"l":"_empty_/Queen.html#","e":false,"i":"","n":"Queen","t":"Queen(c: String, p: Position) extends Piece","d":"","k":"class","x":""},
{"l":"_empty_/Rook.html#","e":false,"i":"","n":"Rook","t":"Rook(c: String, p: Position) extends Piece, Castleable","d":"","k":"class","x":""}];