name: Deploy Scala Documentation

on: 
  push:
    branches: 
      - main


permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 16
      - name: Build and Test
        run: sbt doc
        working-directory: './backend'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './backend/target/scala-3.3.0/api'
          force_orphan: true