# This workflow will run Python unit test with pytest.

name: Scala backend CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: Setup JDK
      uses: actions/setup-java@v3

      with:
        distribution: temurin
        java-version: 16
    
    - run: echo $'final val frontEndUrl = "localhost"\n\nfinal val frontEndPort = 4173' > Config.scala 
      working-directory: './backend/src/main/scala/'

    - name: Build and Test
      run: sbt -v +test
      working-directory: './backend'